DROP DATABASE IF EXISTS FutureTech;
CREATE DATABASE FutureTech;

CREATE USER IF NOT EXISTS 'ft_user'@'%' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON FutureTech.* TO 'ft_user'@'%' IDENTIFIED BY '1234';
FLUSH PRIVILEGES;

USE FutureTech;

DROP TABLE IF EXISTS ToDo;

CREATE TABLE ToDo
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	descr VARCHAR(60) NOT NULL
);

INSERT INTO ToDo VALUES(NULL, "Wohnung putzen");
INSERT INTO ToDo VALUES(NULL, "Essen kochen");

